version: '3.1'

services:
  mysql:
    image: mysql
    restart: always
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: 1
      MULTIPLE_DATABASES: comment_db,user_db,tracker_db
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - '3306:3306'
    volumes:
      - ./initdb:/docker-entrypoint-initdb.d
      
  postgres:
    image: "postgres:11"
    container_name: "my_postgres"
    environment:
      POSTGRES_DB: keyclock_db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password   
    ports:
      - "54320:5432"

  keycloak:
      image: jboss/keycloak
      environment:
        DB_VENDOR: POSTGRES
        DB_ADDR: postgres
        DB_DATABASE: keyclock_db
        DB_USER: user
        DB_SCHEMA: public
        DB_PASSWORD: password
        KEYCLOAK_USER: admin
        KEYCLOAK_PASSWORD: Pa55w0rd
        # Uncomment the line below if you want to specify JDBC parameters. The parameter below is just an example, and it shouldn't be used in production without knowledge. It is highly recommended that you read the PostgreSQL JDBC driver documentation in order to use it.
        #JDBC_PARAMS: "ssl=true"
      ports:
        - 8080:8080
      depends_on:
        - postgres      