server:
  port: 8085
zuul:
  debug:
    request: true
  routes:
    product-service:
      path: /api/products/**
      serviceId: product-service
      stripPrefix: false
    store-service:
      path: /api/stores/**
      serviceId: store-service  
feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: basic